
set(RPC_GENERATED_FILES ${CMAKE_CURRENT_SOURCE_DIR}/callid.hxx  ${CMAKE_CURRENT_SOURCE_DIR}/state.cxx ${CMAKE_CURRENT_SOURCE_DIR}/state.hxx  ${CMAKE_CURRENT_SOURCE_DIR}/stubs.cxx)

set_source_files_properties(${RPC_GENERATED_FILES} PROPERTIES GENERATED TRUE)
